---
- name: Install Apache Web Server on AMI Linux. Upload web page example
  hosts: all
  become: yes
  
  
  vars:
    source_file: index.html
    destin_file: /var/www/html
    
    
  tasks:
  - name: Install Apache Web Server
    yum:  name=httpd state=latest

  - name: Copy index.html to target server
    copy: src={{ source_file }} dest={{ destin_file }} mode=0555
    
  - name: Start Apache and enable it during boot
    service: name=httpd state=started enabled=yes